replicaCount: 1

image:
  repository: ghcr.io/networkengineer-cloud/testrun-operator
  pullPolicy: IfNotPresent
  tag: ""  # defaults to appVersion

imagePullSecrets: []

secretName: testrun-operator-secrets

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
