apiVersion: v1
kind: Service
metadata:
  name: {{ include "testrun-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "testrun-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: webhook
    port: 8080
    targetPort: webhook
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: metrics
    protocol: TCP
